# -*- coding: utf-8 -*-
"""p-129-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IeFBS6n8vV0o5bmDOqAdZs9LvbS-Z4i
"""

from google.colab import files
data_to_load=files.upload()

from google.colab import files
data_to_load=files.upload()

import csv
import pandas as pd

file1='bright_stars.csv'
file2='unit_converted_stars.csv'

d1 = []
d2 = []
with open(file1,'r',encoding='utf8') as f:
    csv_reader =csv.reader(f)
    
    for i in csv_reader:
        d1.append(i)
        
with open(file2,'r',encoding='utf8') as f:
    csv_reader = csv.reader(f)
    
    for i in csv_reader:
        d2.append(i)

h1 = d1[0]
h2 = d2[0]

p_d1 = d1[1:]
p_d2 = d2[1:]

h = h1+h2

p_d =[]

for i in p_d1:
    p_d.append(i)
for j in p_d2:
    p_d.append(j)
with open("total_stars.csv",'w',encoding='utf8') as f:
    csvwriter = csv.writer(f)
    csvwriter.writerow(h)   
    csvwriter.writerows(p_d)
    
df = pd.read_csv('total_stars.csv')
df.tail(8)