# -*- coding: utf-8 -*-
"""p 129-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13yRapEx0B08jEuYy3p5NljB3xKZ5YqJ9
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import csv
df=pd.read_csv("total_stars.csv")
print(df)

df.columns

df.drop(['Unnamed: 0'],axis=1,inplace=True)
df

final_data=df.dropna()
final_data

final_data.reset_index(drop=True,inplace=True)
final_data

final_data.to_csv('final_data.csv')

final_data.info()

final_data.describe()

final_data.head(5)

final_data.dtypes